name: 'File Check Action'
description: 'An action that checks if the LICENSE and README.md files exists'
permissions: write-all

inputs:
  my-token:  # id of input
    description: 'The github token required for octokit initialization'
    required: true
#    default: ''
  my-token-2:  # id of input
    description: 'The github token required for octokit initialization'
    required: true
  pr-status:  # id of input
    description: 'The github token required for octokit initialization'
    required: true
outputs:
  workflow-continue: # id of output
    description: 'This is set to to true if there are no blockers still open, else will be set to false'
  pr-number: # id of output
    description: 'once pr is created the pr number will stored in this variable'  
runs:
  using: 'node12'
  main: 'index.js'