name: 'File Check Action'
description: 'An action that checks if the LICENSE and README.md files exists'
inputs:
  my-token:  # id of input
    description: 'The github token required for octokit initialization'
    required: true
#    default: ''
outputs:
  workflow-continue: # id of output
    description: 'This is set to to true if there are no blockers still open, else will be set to false'
runs:
  using: 'node12'
  main: 'index.js'