name: workflow trigged by merge
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: madhavirkl84/CustomActionTest
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: Trigger another workflow from different repository
        run: |
          curl -XPOST -u "${{ secrets.MY_USER_NAME}}:${{secrets.MY_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/madhavirkl84/CustomActionTest/dispatches \
          --data '{"event_type": "PR closed"}'
      - uses: actions/checkout@v3      
